import type { JSX, PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';

/**
 * Base font app.
 */
const font = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Team Chat App',
    description: 'Generated by create next app',
};

/**
 * Main app component.
 *
 * @param { PropsWithChildren } param0 -
 *
 * @returns { JSX.Element } Main app component.
 */
export default function RootLayout({
    children,
}: PropsWithChildren): JSX.Element {
    return (
        <html lang="en">
            <body className={font.className}>{children}</body>
        </html>
    );
}
