/**
 * Api errors.
 */
export enum ApiErrors {
    INTERNAL_ERROR = 'Internal Error',
    UNAUTHORIZED = 'Unauthorized',
    CHANNELS_POST_ERROR = '[CHANNELS_POST]',
    SERVER_ID_MISSING = 'Server ID missing',
    NAME_NOT_GENERAL = 'Name cannot be "general"',
    CHANNEL_ID_PATCH_ERROR = '[CHANNEL_ID_PATCH]',
    CHANNEL_ID_DELETE_ERROR = '[CHANNEL_ID_DELETE]',
    DIRECT_MESSAGES_GET_ERROR = '[DIRECT_MESSAGES_GET]',
    CONVERSATION_ID_MISSING = 'Conversation ID missing',
    ROOM_MISSING = 'Missing "room" query parameter',
    USERNAME_MISSING = 'Missing "username" query parameter',
    SERVER_MISCONFIGURED = 'Server misconfigured',
    MEMBER_ID_DELETE = '[MEMBER_ID_DELETE]',
    MEMBERS_ID_PATCH = '[MEMBERS_ID_PATCH]',
    MEMBER_ID_MISSING = 'Member ID missing',
    MESSAGES_GET = '[MESSAGES_GET]',
    CHANNEL_ID_MISSING = 'Channel ID missing',
    SERVERS_POST = '[SERVERS_POST]',
    SERVER_ID_PATCH = '[SERVER_ID_PATCH]',
    DELETE_SERVER_ID_ERROR = '[DELETE_SERVER_ID_ERROR]',
    SERVER_ID = '[SERVER_ID]',
    SERVER_ID_LEAVE = '[SERVER_ID_LEAVE]',
    METHOD_NOT_ALLOWED = 'Method not allowed',
    CONTENT_MISSING = 'Content missing',
    SERVER_NOT_FOUND = 'Server not found',
    CHANNEL_NOT_FOUND = 'Channel not found',
    MEMBER_NOT_FOUND = 'Member not found',
    MESSAGES_POST = '[MESSAGES_POST]',
    MESSAGE_ID = '[MESSAGE_ID]',
    MESSAGE_ID_MISSING = 'Message ID missing',
    MESSAGE_NOT_FOUND = 'Message not found',
    DIRECT_MESSAGES_POST = '[DIRECT_MESSAGES_POST]',
    FILE_MISSING = 'File url missing',
    CONVERSATION_NOT_FOUND = 'Conversation not found.',
    DIRECT_MESSAGE_ID = '[DIRECT_MESSAGE_ID]',
    DIRECT_MESSAGE_ID_MISSING = 'Direct message ID missing',
    DIRECT_MESSAGE_ID_NOT_FOUND = 'Direct message not found',
    EQUAL_MESSAGE = 'The content of the message is the same',
}
